openapi: 3.2.0
info:
  version: v1.6
  title: Student Record Code Lookups Course Statuses API
  description: Code Lookups from the Office of the Registrar.
servers:
- url: https://api.ucsb.edu/students
tags:
- name: CourseStatuses
paths:
  /lookups/v1/coursestatuses:
    get:
      tags:
      - CourseStatuses
      operationId: /lookups/v1/coursestatuses
      parameters:
      - name: ucsb-api-version
        in: header
        description: Specific api version to use.
        required: false
        schema:
          type: string
          default: '1.6'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AcademicCourseStatus'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AcademicCourseStatus'
      description: 'Gets the list of course status codes.

        (Data Dictionary - Course Status)'
      security:
      - ucsb-api-key: []
      summary: /lookups/v1/coursestatuses
      x-summary-source: derived
components:
  schemas:
    AcademicCourseStatus:
      type: object
      properties:
        courseStatusCode:
          type: string
        courseStatusTranslation:
          type: string
  securitySchemes:
    ucsb-api-key:
      name: ucsb-api-key
      in: header
      type: apiKey
