# x-archived-from: ucsb-events-openapi.yml
# x-archived-on: 2026-09-16
swagger: '2.0'
info:
  version: v2
  title: Events
  description: Event information aggregated by the Office of Public Affairs and Communications.
  x-source-url: https://developer.ucsb.edu/sites/default/files/openapi/events-v1.api_.out_.yaml
  x-last-validated: '2026-08-30'
  x-operator: institution
host: api.ucsb.edu
basePath: /academics/
schemes:
- https
securityDefinitions:
  ucsb-api-key:
    name: ucsb-api-key
    in: header
    type: apiKey
security:
- ucsb-api-key: []
paths:
  /events/v1:
    get:
      tags:
      - Events
      operationId: /events/v1
      consumes: []
      produces:
      - application/json
      - text/json
      responses:
        '200':
          description: A list of events
      description: Retrieve a list of events
